In [3]:

import numpy as np
 
the_array = np.array([1, 2, 3, 4])
empty_array = np.array([3,4,2,1])
 
new_array = np.append(empty_array, the_array)
print(new_array)

[3 4 2 1 1 2 3 4]


In [4]:
array1d = np.array([1, 2, 3, 4, 5, 6])
array2d = np.array([[1, 2, 3], [4, 5, 6]])
array3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
 
print(array1d)
 
print("-" * 10)
print(array2d)
 
print("-" * 10)
print(array3d)

[1 2 3 4 5 6]
----------
[[1 2 3]
 [4 5 6]]
----------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [6]:
 
array1d = np.arange(5)  # 1 row and 5 columns
print(array1d)
 
array1d = np.arange(0, 12, 2)  # 1 row and 6 columns
print(array1d)
 
array2d = np.arange(0, 12, 2).reshape(2, 3)  # 2 rows 3 columns
print(array2d)
 
array3d = np.arange(9).reshape(3, 3)  # 3 rows and columns
print(array3d)

[0 1 2 3 4]
[ 0  2  4  6  8 10]


ValueError: cannot reshape array of size 5 into shape (2,3)